### ISSUE TITLE
Include the analysis of OPass data

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-postevent-report-generator#11]
This year we also have OPass data exported. We may want to present the data in our report.

**Comment by Lee-W** [comment]
Is Opass data always in the given format?

**Comment by tai271828** [comment]
I suppose "no". However we could always use a well-defined data model to host any given data in the future. The essential attributes of a conference should be always the same. If the format changes, we could always provide the data model a new parser to fetch data in different format.

**Comment by tai271828** [comment]
Implemented with https://github.com/pycontw/pycontw-postevent-report-generator/commit/915d9fdab0c0c1707562ba9defb66efa1c696e8e

After discussing with the sponsorship team, we did not need further feature (yet). Let's stop at this commit.
