### ISSUE TITLE
[Discussion] Fixed Python version?

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-postevent-report-generator#33]
If we are fixing python version, we may lost the convenience feature of package bump version provided by Github e.g. https://github.com/pycontw/pycontw-postevent-report-generator/runs/485045199

pycontw-postevent-report-generator is a small project that may not need to fix python version so restrictly. Trade-off of convenience, better maintenance quality, and fixed python version is worthy discussing.

**Comment by Lee-W** [comment]
It seems pipenv discourages using multiple Python version, the error can be solved by fixing the python version in GitHub workflow. I'll fix it first. We can discuss more on whether we want to fix the version in the future.

**Comment by tai271828** [comment]
Merged the fix and triggered the latest version-bump build. I will update the result here later.

**Comment by tai271828** [comment]
Sad. Another failure is raised. (It looks so weird)

https://github.com/pycontw/pycontw-postevent-report-generator/runs/487271116?check_suite_focus=true

```
/home/runner/work/_temp/673655de-1fa3-4f46-aa94-639b6035f090.sh: line 3: -pipenv: command not found
```

**Comment by Lee-W** [comment]
`-` probably works only in Makefile. I just fixed it in another PR.

**Comment by Lee-W** [comment]
FYI: https://github.com/pypa/pipenv/issues/2683#issuecomment-409330037

**Comment by tai271828** [comment]
Thanks for sharing the context and PR. For now the merged repo looks good https://github.com/pycontw/pycontw-postevent-report-generator/actions/runs/50632090 . However Bump Version still a bit weird for me. https://github.com/pycontw/pycontw-postevent-report-generator/actions/runs/50632089

Bump version will be another type of issue if nothing still runs in the future. Let's close this ticket (and re-open it if necessary in the future) and see how the automation goes.
